// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm5rvzghM0edkJMv7Z9wXRPqlEd1l9Ank',
    appId: '1:28731406413:web:0332590221da2b4e784404',
    messagingSenderId: '28731406413',
    projectId: 'beacon-detector-fb-568ab',
    authDomain: 'beacon-detector-fb-568ab.firebaseapp.com',
    storageBucket: 'beacon-detector-fb-568ab.appspot.com',
    measurementId: 'G-Y6H4GD0TGW',
    databaseURL: 'https://beacon-detector-fb-568ab.firebaseio.com',  // Bu satırı ekledik
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLa6p1BRl2TNlz4229q_iPW-mBk5VusuM',
    appId: '1:28731406413:android:782a1f72457601f1784404',
    messagingSenderId: '28731406413',
    projectId: 'beacon-detector-fb-568ab',
    storageBucket: 'beacon-detector-fb-568ab.appspot.com',
    databaseURL: 'https://beacon-detector-fb-568ab.firebaseio.com',  // Bu satırı ekledik
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjtFmWZD4fP6pNZjVG9xgUzI-jBvVbKDA',
    appId: '1:28731406413:ios:7217e2b12e0717e9784404',
    messagingSenderId: '28731406413',
    projectId: 'beacon-detector-fb-568ab',
    storageBucket: 'beacon-detector-fb-568ab.appspot.com',
    iosBundleId: 'com.example.beaconDetectorFutter',
    databaseURL: 'https://beacon-detector-fb-568ab.firebaseio.com',  // Bu satırı ekledik
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjtFmWZD4fP6pNZjVG9xgUzI-jBvVbKDA',
    appId: '1:28731406413:ios:7217e2b12e0717e9784404',
    messagingSenderId: '28731406413',
    projectId: 'beacon-detector-fb-568ab',
    storageBucket: 'beacon-detector-fb-568ab.appspot.com',
    iosBundleId: 'com.example.beaconDetectorFutter',
    databaseURL: 'https://beacon-detector-fb-568ab.firebaseio.com',  // Bu satırı ekledik
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm5rvzghM0edkJMv7Z9wXRPqlEd1l9Ank',
    appId: '1:28731406413:web:955db08d26040ba0784404',
    messagingSenderId: '28731406413',
    projectId: 'beacon-detector-fb-568ab',
    authDomain: 'beacon-detector-fb-568ab.firebaseapp.com',
    storageBucket: 'beacon-detector-fb-568ab.appspot.com',
    measurementId: 'G-SL2QEZFC23',
    databaseURL: 'https://beacon-detector-fb-568ab.firebaseio.com',  // Bu satırı ekledik
  );
}
